name: Build Test


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # ** in case of manual start of tests needed!
  #workflow_dispatch:

jobs:

  # ** name of the job
  build-test:
    runs-on: ubuntu-latest
    # ** if another job has to be performed first  
    #needs: <the name of the job that need to be finished before starting this job>
    strategy:
      matrix:
        # ** if more than one version neeeded. For example [18.x, 20.x, 22.x]
        node-version: [20.x]
    steps:
    - name: Checkout code  
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies 
      run: npm install
    # ** Run app if neccessary
    #- name: Run app
    #  run: npm run start &
    - name: Run app tests
      run: npm run test
  
  #jobfor deployment in Render.com    
  deploy:
    runs-on: ubuntu-latest
   #check if commit is in main
   #if gihub.ref == 'refs/heads/main' 
    needs: build-test
    steps:
    - name: Deploy to production
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api_key: ${{ secrets.MY_RENDER_API_KEY }}
        wait_deploy: true

