services:
  resellerapp:
    container_name: resellerapp
    image: milenzapryanov/resellerapp:1.0
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/resellerdb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOUCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=my-secret-pw
    networks:
      - backend
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=resellerdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpass 
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
volumes:
  mysql-data: